# Generated by Django 3.2 on 2022-05-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='movie_char',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shot',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
