# Generated by Django 3.2 on 2022-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0005_alter_shot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
